# Generated by Django 4.1.9 on 2023-05-24 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_customuser_senha1_remove_customuser_senha2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='usuario',
        ),
    ]
